# Generated by Django 4.2 on 2023-04-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_comments_commented_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='liked_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Base.tweets'),
        ),
    ]
