# Generated by Django 4.2 on 2023-04-09 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0005_alter_tweets_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('bookmarked_in', models.ManyToManyField(blank=True, related_name='Btweets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Btweet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
