# Generated by Django 4.2 on 2023-04-09 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0006_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='bookmarked_in',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='content',
        ),
        migrations.RemoveField(
            model_name='bookmarks',
            name='user',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='Isbookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='bookmarked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='bookmarked_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.tweets'),
        ),
    ]
