# Generated by Django 4.2 on 2023-04-09 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0008_delete_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('tweets_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Base.tweets')),
                ('bookmarked_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('Base.tweets',),
        ),
    ]
