# Generated by Django 4.2 on 2023-04-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_bookmarks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmarks',
        ),
    ]
