# Generated by Django 4.2 on 2023-04-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_tweets_bookmarked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='bookmarked',
        ),
    ]
