# Generated by Django 4.2 on 2023-04-09 17:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0012_remove_tweets_bookmarked'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='bookmarked_by',
            field=models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
