# Generated by Django 4.2 on 2023-04-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Base', '0014_remove_tweets_bookmarked_by_friendlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='Btweets', to='Base.tweets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Buser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
